import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finance-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="flex justify-center bg-whitePrimary min-h-screen">
          <div className="flex w-[390px] px-[28px] bg-whitePrimary overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
