import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import Root from "../Context/Root";

const montSerrat = Montserrat({
  weight: ["200", "300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Finance-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${montSerrat.className}`}>
          <div className="w-full h-screen flex justify-center bg-whitePrimary">
            <div className="w-full bg-whitePrimary overflow-x-hidden">
              <Root>{children}</Root>
            </div>
          </div>
      </body>
    </html>
  );
}
